db_connection: postgresql://fred:password@127.0.0.1:5432/fred
grpc_port: 50051
logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        syslog:
            format: 'fred-fileman: %(levelname)-8s %(module)s:%(funcName)s:%(lineno)s %(message)s'
    handlers:
        syslog:
            class: logging.handlers.SysLogHandler
            formatter: syslog
            address: '/dev/log'
    loggers:
        '':
            handlers: [syslog]
            level: INFO
max_workers: 32
storage_root: /var/lib/fileman
