#Logging options
# * device - specifies devices used for logging
#  * possible values: console, file, syslog
#  * is a multiple option
# * min_severity - events at least this severity are logged
#  * severities in ascending order: trace, debug, info, warning, error, critical
#  * can be overriden by particular device option
# * grpc_library - enable logging of events from gRPC library
[log]
device       = console
device       = file
device       = syslog
min_severity = debug
grpc_library = yes

#Logging into console options
# * min_severity - events at least this severity are logged into console
#  * overrides log.min_severity option
# * output_stream - where to log
#  * possible values: stderr, stdout
#  * default is stderr
# * color_mode - use colorized output
#  * possible values: always, auto, never
#  * default is never
[log.console]
min_severity  = info
output_stream = stderr
color_mode    = auto

#Logging into file options
# * file_name - file name for logging
# * min_severity - events at least this severity are logged into file
#  * overrides log.min_severity option
[log.file]
file_name    = /var/log/fred-zone-service.log
min_severity = trace

#Logging by syslog options
# * ident - what ident to log with (default is an empty string)
# * min_severity - events at least this severity are logged into file
#  * overrides log.min_severity option
# * facility - what LOG_LOCALx facility to log with (x in range 0..7)
#  * if does not present use LOG_USER facility
[log.syslog]
ident        = fred-zone-generator
min_severity = debug
facility     = 2

#Zone service options
# * connect_to - server's address where client has to connect
[zone_service]
connect_to = [::1]:50053

#Generated zones options:
# * zones - list of zone names to be generated; if no zones are specified at all, list
#           of zones is downloaded from server
[generate]
zones = cr