[database]
host = 127.0.0.1
port = 5432
name = fred
user = fred
password = fred
timeout = 60

[nameservice]
host = 127.0.0.1
port = 2809
context = fred

[log]
type = 2
level = 7
file = /var/log/fred-pifd.log
syslog_facility = 7

[registry]
restricted_handles = false
disable_epp_notifier = false
lock_epp_commands = true
nsset_level = 3
system_registrar = REG-SYSTEM
authinfo_length_min = 8
