[log]
device       = syslog
min_severity = debug
grpc_library = yes

[log.syslog]
min_severity = debug
facility     = 7

[database]
host     = localhost
port     = 5432
dbname   = fred

[database.ro]
user     = fred
password = fred

[database.rw]
user     = fred
password = fred

[fred]
registrar_originator = REG-SYSTEM

[identity]
listen  = 127.0.0.1:2243
service = IdentityChecker
service = IdentityManager
service = IdentityUser
service = Diagnostics
