 # Logging options
#  * device - specifies devices used for logging
#   * possible values: console, file, syslog
#   * is a multiple option
#  * min_severity - events at least this severity are logged
#   * severities in ascending order: trace, debug, info, warning, error, critical
#   * can be overriden by particular device option
#  * grpc_library - enable logging of events from gRPC library
[log]
device       = syslog
min_severity = debug
grpc_library = yes

# Logging into console options
#  * min_severity - events at least this severity are logged into console
#   * overrides log.min_severity option
#  * output_stream - where to log
#   * possible values: stderr, stdout
#   * default is stderr
#  * color_mode - use colorized output
#   * possible values: always, auto, never
#   * default is never
# [log.console]
# min_severity  = info
# output_stream = stderr
# color_mode    = auto

# Logging into file options
#  * file_name - file name for logging
#  * min_severity - events at least this severity are logged into file
#   * overrides log.min_severity option
# [log.file]
# file_name    = /var/log/fred-dbreport-services.log
# min_severity = trace

# Logging by syslog options
#  * ident - what ident to log with (default is an empty string)
#  * min_severity - events at least this severity are logged into file
#   * overrides log.min_severity option
#  * facility - what LOG_LOCALx facility to log with (x in range 0..7)
#   * if does not present use LOG_USER facility
[log.syslog]
min_severity = debug
facility     = 7

# Common database options (can be overriden by particular database options)
#  * host - name of host to connect to
#  * host_addr - IP address of host to connect to
#  * port - port number to connect to at the server host
#  * user - PostgreSQL user name to connect as
#  * dbname - the database name
#  * password - password used for password authentication
#  * connect_timeout - maximum wait for connection
#   * in seconds
#   * zero or not specified means wait indefinitely
#   * [It is not recommended to use a timeout of less than 2 seconds.]
#  * schema - database schema containing report functions
#   * default value is 'report'
#   * can not be overriden by particular database options
[database]
host     = 127.0.0.1
port     = 5432
dbname   = fred
schema   = report

# Database read-only access options (overrides database options)
[database.ro]
user     = fred
password = fred

# Database read/write access options (overrides database options)
[database.rw]
user     = fred
password = fred

# Server options
#  * listen - server's listen address
#  * service - gRPC service to run
#   * possible values: ReportUser, ReportManager
#   * is a multiple option
[dbreport]
listen  = 192.168.1.1:2242
service = ReportManager
service = ReportUser
service = Diagnostics
