[log]
device = syslog
min_severity = debug

[log.syslog]
facility = 7
min_severity = info

[database]
host = 127.0.0.1
port = 5432
user = fred
dbname = fred
password = fred

[logger]
listen = 192.168.1.1:15006
monitoring_hosts_file = /etc/fred/monitoring_hosts.conf

