[log]
device = syslog
min_severity = info

[log.syslog]
facility = 7

[database]
host = 127.0.0.1
port = 5432
user = fred
dbname = fred
password = fred

[registry]
listen = 192.168.1.1:15005

[fred]
registrar_originator = REG-SYSTEM

