[database]
host = 127.0.0.1
port = 5432
dbname = fred
user = fred
password = fred

[log]
device = syslog
min_severity = debug

[log.syslog]
facility = 7

[logger]
monitoring_hosts_file = /etc/fred/monitoring_hosts.conf
log_entry_cache_size_max = 2000
session_cache_size_max = 1000

[nameservice]
host = 127.0.0.1
port = 2809
context = fred
orb_args = -ORBnativeCharCodeSet UTF-8 -ORBendPoint giop:tcp::2236
service = LoggerNew
