[main]
#
# Fred2PDF
# Example of the configuration file
#
trml_module_name = trml2pdf
module_path = #/usr/lib/tinyerp-server/report/render
true_type_path = /usr/share/fonts/truetype/freefont

# Font names MUST be in this order:
# basic style, obligue, bold, bold-obligue
default_font_ttf = FreeSans.ttf FreeSansOblique.ttf FreeSansBold.ttf FreeSansBoldOblique.ttf
