[database]
host = 127.0.0.1
port = 5432
name = fred
user = fred
password = password
timeout = 60

[nameservice]
host = 127.0.0.1
port = 2809
context = fred

[log]
type = 2
level = 7
file = /var/log/fred-accifd.log
syslog_facility = 7
