[database]
host = 127.0.0.1
port = 5432
name = fred
user = fred
password = fred
timeout = 60

[nameservice]
host = 127.0.0.1
port = 2809
context = fred

[log]
type = 2
level = 7
file = /var/log/fred-akmd.log
syslog_facility = 7

[logger_client]
corba_ns_logger_name = LoggerNew

[akmd]
automatically_managed_keyset_prefix = AUTO-
automatically_managed_keyset_registrar = REG-SYSTEM
automatically_managed_keyset_tech_contact = REG-SYSTEM
automatically_managed_keyset_zones = cz
disable_notifier = false
enable_request_logger = true
