# Logging options
# * device - specifies devices used for logging
#  * possible values: console, file, syslog
#  * is a multiple option
# * min_severity - events at least this severity are logged
#  * severities in ascending order: trace, debug, info, warning, error, critical
#  * can be overriden by particular device option
# * grpc_library - enable logging of events from gRPC library
[log]
device       = console
device       = file
device       = syslog
min_severity = debug
grpc_library = yes

# Logging into console options
# * min_severity - events at least this severity are logged into console
#  * overrides log.min_severity option
# * output_stream - where to log
#  * possible values: stderr, stdout
#  * default is stderr
# * color_mode - use colorized output
#  * possible values: always, auto, never
#  * default is never
[log.console]
min_severity  = info
output_stream = stderr
color_mode    = auto

# Logging into file options
# * file_name - file name for logging
# * min_severity - events at least this severity are logged into file
#  * overrides log.min_severity option
[log.file]
file_name    = fred-notify-object-state-changes.log
min_severity = trace

# Logging by syslog options
# * ident - what ident to log with (default is an empty string)
# * min_severity - events at least this severity are logged into file
#  * overrides log.min_severity option
# * facility - what LOG_LOCALx facility to log with (x in range 0..7)
#  * if does not present use LOG_USER facility
[log.syslog]
ident        = fred-notify-object-state-changes
min_severity = trace
facility     = 2

# Database options
# * host - name of host to connect to
# * host_addr - IP address of host to connect to
# * port - port number to connect to at the server host
# * user - PostgreSQL user name to connect as
# * dbname - the database name
# * password - password used for password authentication
# * connect_timeout - maximum wait for connection
#  * in seconds
#  * zero or not specified means wait indefinitely
#  * [It is not recommended to use a timeout of less than 2 seconds.]
[database]
host     = localhost
port     = 5432
dbname   = fred
user     = fred
password = fred

# Messenger options
# * endpoint - URI of Fred.Messenger.Api.Email gRPC service
# * archive - archive email message
[messenger]
endpoint = localhost:50052
archive = yes

[notification]
# * config_file - json configuration of which event(s) will be notified for which object(s) to which group(s) of recipients
# * state_age_days_max - do not notify state changes older then state_age_days_max days
# * notifications_max - how many events to process in one run (0 = no limit)
# * generic_email_prefix - how to build generic email address(es) of the contact of the domain. Can be present multiple times to build more addresses.
#  * one more prefix (name of the domain) is used implicitly
config_file = /etc/fred/fred-notify-object-state-changes.json
state_age_days_max = 14
notifications_max = 0
generic_email_prefix = info
generic_email_prefix = kontakt
generic_email_prefix = postmaster
