---
db_connection: postgresql://messenger:password@localhost:5432/messenger
delivery_options:
    host: imap.example.com
    port: 993
    ssl: 1
    tls: 0
    username: imapuser
    password: imappass
fileman_netloc: localhost:50051
fred_db_connection: postgresql://fred:password@localhost:5432/fred
grpc_options:
    # Lower max receive message size to 3 MB. 4 MB is default.
    # Outcomming messanges are slightly larged than incoming, so we need to make an offset for that.
    - [grpc.max_receive_message_length, 3145728]
grpc_port: 50052
logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        syslog:
            format: 'fred-messenger: %(levelname)-8s %(module)s:%(funcName)s:%(lineno)s %(message)s'
    handlers:
        syslog:
            class: logging.handlers.SysLogHandler
            formatter: syslog
            address: '/dev/log'
    loggers:
        '':
            handlers: [syslog]
            level: INFO

msgid_domain: example.com
processors:
    email:
        # Comment out when not used to skip database searches.
        - class: messenger.processors.BlockedEmailProcessor
        - class: messenger.processors.SmimeEmailProcessor
          smime_certificates:
              - ["/path/to/key", "/path/to/cert"]
              - ["/path/to/different/key", "/path/to/different/cert"]
    # Commented out to skip database searches
    # sms:
    #     - class: messenger.processors.BlockedSmsProcessor
    # Commented out to skip database searches
    # letter:
    #     - class: messenger.processors.BlockedLetterProcessor

senders:
    # E-mails
    smtp:
        backend: messenger.backends.email.SmtpBackend
        options:
            host: imap.example.com
            port: 993
            username: imapuser
            password: imapuser
            use_ssl: 1
            use_tls: 0
            timeout: 5
            secretary_url: https://secretary.example.com/api/
            secretary_timeout: 3
            secretary_token: SECRETARY_TOKEN
            default_from: support@example.com
            sender: sdn@example.com
