###############################################################################
#                        PYFRED Configuration File                            #
###############################################################################
#
# The detailed description of configuration can be found in README. Consider
# reading it before you make any changes to this file.
# Note that this is the default configuration which might work (or not)
# depending on many circumstances
# (i.e. location of postgresql server, nameservice, ...)

###
### Basic configuration of PYFRED
###
# These settings are common to all modules.
[General]
# List of modules to load (separated by spaces)
modules=genzone filemanager
# pidfile is the file where the server records its process id
#pidfile=/var/run/fred-pyfred.pid
# Host where PYFRED listens for CORBA calls
# (empty value binds PYFRED to all available IP addresses)
#host=
# Port where PYFRED listens for CORBA calls
port=2225

#### Database settings
# Database host or empty value for Unix socket
dbhost=localhost
# Database port
dbport=5432
# Database name
dbname=fred
# Database user name
dbuser=fred
# Database password (if required)
dbpassword=fred

#### CORBA nameservice settings
# Nameservice host
nshost=localhost
# Nameservice port
nsport=2809
# Nameservice context (check with the ``namectl`` command)
nscontext=fred

#### Logging settings
# Log handler selection:
# * syslog  (see also logfacility option)
# * file    (see also logfilename option)
# * console (can be used only if server is not daemonized after start)
loghandler=syslog
# Log level
# * debug
# * info
# * notice
# * warning
# * error
# * critical
# * alert
# * emerg
loglevel=error
# Specify syslog facility (if handler is syslog)
logfacility=local1
# Specify log file (if handler is a file)
logfilename=/var/log/fred-pyfred.log

###
### Zone-generating module configuration
###
[Genzone]
# DS record digest algorithm sha1|sha256
#   default: sha1
dsrecord_algo = sha1

#### CORBA objects lifetime settings
# Timeout (seconds) after which objects are considered idle
#   default: 3600
#idletreshold=3600
# Interval (seconds) between checks for idle objects
#   default: 60
#checkperiod=60


###
### File-managing module configuration
###
[FileManager]
# Absolute path of the directory to store managed files
rootdir=/var/lib/pyfred/filemanager/

#### CORBA objects lifetime settings
# Timeout (seconds) after which objects are considered idle
#idletreshold=3600
# Interval (seconds) between checks for idle objects
#checkperiod=60
