###############################################################################
#                        PYFRED Genzone Configuration File                    #
###############################################################################
#
# The detailed description of configuration can be found in README. Consider
# reading it before you make any changes to this file.

[General]
modules=genzone
port=2231

dbhost=localhost
dbport=5432
dbname=fred
dbuser=fred
dbpassword=fred

nshost=127.0.0.1
nsport=2809
nscontext=fred

loghandler=syslog
loglevel=error
logfacility=local1
logfilename=/var/log/fred-pyfred.log

[Genzone]
dsrecord_algo = sha1
#idletreshold=3600
#checkperiod=60

