###############################################################################
#                        PYFRED Filemanager Configuration File                #
###############################################################################
#
# The detailed description of configuration can be found in README. Consider
# reading it before you make any changes to this file.

[General]
modules=filemanager
#pidfile=/var/run/fred-pyfred.pid
#host=
port=2232

dbhost=localhost
dbport=5432
dbname=fred
dbuser=fred
dbpassword=

nshost=localhost
nsport=2809
nscontext=fred

loghandler=syslog
loglevel=error
logfacility=local1
#logfilename=/var/log/fred-pyfred.log

[FileManager]
rootdir=/var/lib/pyfred/filemanager/
#idletreshold=3600
#checkperiod=60

